set(_CATKIN_CURRENT_PACKAGE "manager_node")
set(manager_node_VERSION "0.0.0")
set(manager_node_MAINTAINER "kejia <kejia@todo.todo>")
set(manager_node_PACKAGE_FORMAT "1")
set(manager_node_BUILD_DEPENDS "roscpp" "std_msgs")
set(manager_node_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(manager_node_BUILDTOOL_DEPENDS "catkin")
set(manager_node_BUILDTOOL_EXPORT_DEPENDS )
set(manager_node_EXEC_DEPENDS "roscpp" "std_msgs")
set(manager_node_RUN_DEPENDS "roscpp" "std_msgs")
set(manager_node_TEST_DEPENDS )
set(manager_node_DOC_DEPENDS )
set(manager_node_DEPRECATED "")